title: dabi's blog
description: 개발과 일상을 기록하는 블로그
url: "https://ibiseolsin.github.io"
baseurl: "/blog"
theme: minima
minima:
  skin: classic

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - about.md

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
